version: '3.9'
services:
  mongo:
    image: mongo:6.0.1-focal
    ports:
      - 27017:27017
  api:
    tty: true
    stdin_open: true
    env_file: ./.env
    build:
      context: ./packages/api
      dockerfile: Dockerfile
    ports:
      - 5006:5006
    dns:
      - 8.8.8.8
  web:
    tty: true
    stdin_open: true
    build:
      context: ./packages/web
      dockerfile: Dockerfile
    ports:
      - 5005:5005
  proxy:
    tty: true
    stdin_open: true
    build:
      context: ./packages/proxy
      dockerfile: Dockerfile
    ports:
      - 5000:5000
